### ISSUE TITLE
Using with ESPHOME / home assistant

### ISSUE THREAD

**Issue by bleughb** [Flameeyes/esphome-lg-pqrcuds0#1]
Hi,
I'm quite new to ESPhome / home assistant , 
i've spent a good day or so trying to figure out how your code works and how to get it to be installed!, i'm failing

Figured out that to include the .h file you need to reference the local directory with a folder in the esphome dir - i just copied the examples i found....... 

external_components:
  - source:
      type: local
      path: my_components

My latest issue is the  line -
entity_id: ${reference_temperature} 

the compiler oming up with the error
"Entity ID must have exactly one dot in it."

then when you remove the braces, it compiles with another error
and when you add a . it comes up with another

' ' ' 
/config/esphome/esphome-web-df7188.yaml:60:30: error: expected type-specifier before 'LgHvac'
       auto lg_pqrcuds0 = new LgHvac(id(wall_uart), id(reference_temperature));
                              ^~~~~~
/config/esphome/esphome-web-df7188.yaml:62:26: error: could not convert '{lg_pqrcuds0}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::climate::Climate*>'
       return {lg_pqrcuds0};
                          ^
*** [/data/esphome-web-df7188/.pioenvs/esphome-web-df7188/src/main.cpp.o] Error 1
' ' '

**Comment by Flameeyes** [comment]
I think I might need to update the example a little bit for the more recent versions of ESPHome configs.

Though unless something changed on the last couple of months, the include just needs to be in the same directory as the config itself.

As for the reference temperature, you need to provide it with a sensor ID from your Home Assistant installation that represent the temperature of the room you want to control. I use an average between a Dyson fan temperature and a thermometer on the back of my chair for my home office climate.

**Comment by bleughb** [comment]
Thankyou for the quick reply!
I tried putting that .h file 'everywhere' just to see if it would pickup at all...zilch till I added the local reference

have renamed one of my temperature sensors to reference_temperature to match yours, but still getting
an error when compiling it

..........


INFO ESPHome 2023.5.5
INFO Reading configuration /config/esphome/esphome-web-df7188.yaml...
Failed config

sensor.homeassistant: [source /config/esphome/esphome-web-df7188.yaml:52]
  platform: homeassistant
  id: reference_temperature
  internal: True
  
  Entity ID must have exactly one dot in it.
  entity_id: ${reference_temperature}


the {} are confusing me a little -

**Comment by Flameeyes** [comment]
Your file should look something like:

```
# SPDX-FileCopyrightText: 2021 Diego Elio Pettenò
#
# SPDX-License-Identifier: 0BSD

esphome:
  name: study-climate
  friendly_name: Study Climate

  includes:
    - lg-pqrcuds0.h

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: recommended

uart:
  - id: wall_uart
    tx_pin: GPIO25
    rx_pin: GPIO26
    baud_rate: 104

sensor:
  - id: reference_temperature
    platform: homeassistant
    internal: true
    entity_id: sensor.study_temperature  # This needs to exist in Home Assistant already!

climate:
  - platform: custom
    lambda: |-
      auto lg_pqrcuds0 = new LgHvac(id(wall_uart), id(reference_temperature));
      App.register_component(lg_pqrcuds0);
      return {lg_pqrcuds0};

    climates:
      - name: Climate
 ```

And then the `.h` file should be in `/config/esphome` of your Home Assistant installation just like the `yml` file.

Note that over there I have omitted the various basic config for API and Home Assistant integration as well as WiFi configuration.
